### ISSUE TITLE
Getting issue while loading model

### ISSUE THREAD

**Issue by vijender412** [abhishekkrthakur/bert-sentiment#1]
Getting below issue while loading the model in local system. Model was trained on colab. 

```
Traceback (most recent call last):
  File "app.py", line 74, in <module>
    MODEL.load_state_dict(torch.load(config.MODEL_PATH, map_location=torch.device('cpu'))) #New created
  File "C:\Users\Vijender\Downloads\bert_sentiment\lib\site-packages\torch\nn\modules\module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BERTBaseUncased:
        Missing key(s) in state_dict: "bert.embeddings.word_embeddings.weight", "bert.embeddings.position_embeddings.weight", "bert.embeddings.token_type_embeddings.weight", "bert.embeddings.LayerNorm.weight", "bert.embeddings.LayerNorm.bias", "bert.encoder.layer.0.attention.self.query.weight", "bert.encoder.layer.0.attention.self.query.bias",
```

**Comment by abhishekkrthakur** [comment]
did you use data parallel to train the model?

**Comment by vijender412** [comment]
@abhishekkrthakur  Yes used data parallel while training

**Comment by abhishekkrthakur** [comment]
does your bert_base_path has bert base uncased model files?

**Comment by vijender412** [comment]
@abhishekkrthakur Fixed the issue was with data parallel. I local i was not making use of "MODEL = nn.DataParallel(MODEL)". Now working with this. Can you help me understand the use of DataParallel and if it does require after training also? 
Thanks for quick replying. Good to close the issue

**Comment by abhishekkrthakur** [comment]
DataParallel is used only when you have multiple GPUs during training.
If you used it in training, you have to use in inference but there are other ways too.

Closing this issue for now. :)

**Comment by nipunsadvilkar** [comment]
@abhishekkrthakur :  Can you give any leads on how to load `DataParallel` GPU model on CPU?
As per [pytorch docs](https://pytorch.org/tutorials/beginner/saving_loading_models.html#save-on-gpu-load-on-cpu) tried following but still raises above `RuntimeError`

```python
device = torch.device('cpu')
model = TheModelClass(*args, **kwargs)
model.load_state_dict(torch.load(PATH, map_location=device))
```
