### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by thanish** [abhishekkrthakur/bert-sentiment#6]
Hi I'm getting the below error when I run the train script. Can you help me 

File "C:\Users\thanisb\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py", line 1724, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
[Finished in 33.4s with exit code 1]

**Comment by rohitghule1995** [comment]
@thanish did you get any solution for this?

**Comment by thanish** [comment]
@rohitghule1995  No I did not. I almost forgot what I raised it for and moved on when I did not get response 2nad half months back

**Comment by abhishekkrthakur** [comment]
Unfortunately just error and not saying how and what caused it and not the full stacktrace won't result in any kind of response.
